### ISSUE TITLE
After upgarding to 4.1.2 from 3.0.1 problem with <Protocol> <Address> as4 subfolder

### ISSUE THREAD

**Issue by ilicalex** [holodeck-b2b/Holodeck-B2B#107]
After upgrading Holodeckb2b from 3.0.1 to 4.1.2 we noticed change in P-Modes.
We would like to avoid informing all TSOs for gas (ENTSOG) about changed path in our address.
Instead of 
`...
<Leg>
        <Protocol>
            <Address>http://localhost:9090/services</Address>
        </Protocol>
...`

It works if we set:
`<Address>http://localhost:9090/holodeckb2b/as4</Address>`

We are also able to rename holdeckb2b into services in axis2.xml (config).
However, we cannot avoid specifying as4 subfolder.
How to preserve same address (without AS4 subfolder) and avoid error in holodeckb2b.log on receive side:
(HttpConnection...)[ERROR] org.apache.axis2.engine.AxisEngine - The service cannot be found for the endpoint reference (EPR) fe80:0:0:0:383f:3a12:d8ae:8d8c%12/services

**Comment by Mr-Rocky** [comment]
We solved this problem by using option URL rewrite in IIS Manager. We added rule to add `/as4` at the end of url in case we get query to `.../services`. With this we had to also set listening port of the service to different one (let's say from 9090 to 9091).

**Comment by ilicalex** [comment]
It works
