### ISSUE TITLE
Content-Disposition in MIME body

### ISSUE THREAD

**Issue by JoshGlue** [holodeck-b2b/Holodeck-B2B#114]
In section 5.1.9 of the AS4 Specification (http://docs.oasis-open.org/ebxml-msg/ebms/v3.0/profiles/AS4-profile/v1.0/os/AS4-profile-v1.0-os.html#__RefHeading__26456_1909778835) is stated:

>  The “Content-disposition” header on MIME body parts, when used, MUST carry file   name information. Implementations MUST support the setting (when sending) and reading (when receiving) of “Content-disposition” header

I did not find a setting on how to add this header to the payload. Is this header supported in Holodeck or does this need to be implemented?

**Comment by sfieten** [comment]
Hi Josh,
setting of the _Content-Disposition_ MIME header on the MIME body parts of payloads is currently not supported in Holodeck B2B. Therefore there is also no method of setting this value. If the file name of a payload needs to be exchanged between trading partners it would also be better to define and use a specific _Part Property_ as defined by the ebMS V3 Core Specification.
