### ISSUE TITLE
org.holodeckb2b.common.VersionInfo is missing

### ISSUE THREAD

**Issue by asd1245dss** [holodeck-b2b/Holodeck-B2B#115]
Hello,it seems that  the `org.holodeckb2b.common.VersionInfo` is missing,anyone could help me what's wrong with this ?
![image](https://user-images.githubusercontent.com/2149974/113229029-b7d16500-92c8-11eb-8fca-d16f013d7e60.png)

**Comment by AnnapoorniS** [comment]
Could you help with how did you fix this?
