### ISSUE TITLE
Refactoring HolodeckB2BServer

### ISSUE THREAD

**Issue by ConradMoeller** [holodeck-b2b/Holodeck-B2B#116]
This is a change request to refactor the class org.holodeckb2b.core.HolodeckB2BServer to be able to use HolodeckB2B running on windows as a service using Apache Commons Daemon (https://commons.apache.org/proper/commons-daemon/procrun.html)

ToDo

1. refactoring of org.holodeckb2b.core.HolodeckB2BServer (encapsulate the server start method and make accessible to public)
2. implementing a bootstrap class to use it convenient with Apache Commons Daemon
3. add a script to install the Windows Service in distribution (bin-folder)

view branch 'winservice_issue116' in fork https://github.com/ConradMoeller/Holodeck-B2B

BR Conrad

**Comment by RenateS** [comment]
Thank you Conrad! We will review and get back to you.

**Comment by sfieten** [comment]
Version 5.3.1 now includes support Apache Commons Daemon in _jvm mode_. The class to use is `org.holodeckb2b.core.HolodeckB2BServer` and the start and stop methods `main` respectively `shutdown`. The other parameters can be derived from the `startServer.bat` script.
