### ISSUE TITLE
Java 8 EOL

### ISSUE THREAD

**Issue by Footur** [holodeck-b2b/Holodeck-B2B#119]
Java 8 is required for the use of Holodeck B2B. Support for Java 8 expires in March 2022. Will Java 11 or Java 17 be supported until then?

[Oracle Java SE Support Roadmap](https://www.oracle.com/java/technologies/java-se-support-roadmap.html)

**Comment by RenateS** [comment]
Holodeck B2B already supports Java 11 since version 4. I see that 'or higher' is missing in the Readme regarding the Java version. I'll add it right away, thanks for pointing it out!
