### ISSUE TITLE
Delays in transmission process

### ISSUE THREAD

**Issue by sopgreg** [holodeck-b2b/Holodeck-B2B#125]
I'm experiencing long delays between the transmission statuses of up to a minute (without retries), see screenshot. Is this normal behaviour which can be configured, or is it a bug?

![grafik](https://user-images.githubusercontent.com/33895520/148377149-9d832952-675a-4a31-a468-a2507f0b3c58.png)

**Comment by sopgreg** [comment]
Some further observations:

- the 10 second gap between `READY_TO_PUSH` and `PROCESSING` seems to be the regular interval of the `SenderWorker`. Reducing the interval to like two seconds will also have an effect. It would be useful if the few lines of code pro processing a message in `SenderWorker` could be executed right away when a message is set to `READY_FOR_PUSH`, without any interval inbetween
- the 5 second gap between `SENDING` and `TRANSPORT_FAILURE` is okay and expected, this is a regular 5000ms HTTP timeout in my case (other MSH not reachable)
- the 40 seconds delay between `TRANSPORT_FAILURE` and `FAILURE` seems to be again a result of the interval of the `RetransmissionWorker` plus some additional delay. This should be eliminated completely, if no retransmission is required per Leg definition

**Comment by RenateS** [comment]
This is normal behaviour. Such a long delay can indeed happen in a situation where the maximum intervals apply. As most users do use retries, immediately checking retry configuration after a transmission failure would not have a major impact on performance. We may look into this for a future version but it has lower priority. To reduce the 40 second delay you could decrease the worker interval of the _RetransmissionWorker_.
