### ISSUE TITLE
Is there a way to control either payload file will be copied or moved through configuration?

### ISSUE THREAD

**Issue by ilicalex** [holodeck-b2b/Holodeck-B2B#129]
The default behaviour of COPY was changed to MOVE the files defined through payloads paths from the source path to the server (at least in HolodeckB2B version 5, probably the change was done in one of versions 4.x). We want to be able to use COPY for all files provided by payload path and preserve the payloads on original location. 
Ideally this option should be in the configuration  file: holodeckb2b.xml.

Thank you in advance and best regards!

**Comment by sfieten** [comment]
As documented in the [change log of the file based back-end](https://github.com/holodeck-b2b/file-backend/blob/master/CHANGELOG.MD) the processing of the payload files indeed has changed with the default now being that the files are deleted / moved. As described in the [API specification of the back-end](https://github.com/holodeck-b2b/file-backend/blob/master/api_specification.md) you can however control this behaviour and set as default to leave the files untouched.
