### ISSUE TITLE
CVEs in outdated libs wss4j and xmlsec

### ISSUE THREAD

**Issue by sopgreg** [holodeck-b2b/Holodeck-B2B#135]
The versions used for wss4j (2.2.2) and xmlsec (2.1.2) are several years old and partially also contain CVEs.

![grafik](https://user-images.githubusercontent.com/33895520/192728836-37cf7f4c-1845-4b17-86b0-6a7dd1ad9f05.png)

See also:

https://ws.apache.org/wss4j/index.html
https://santuario.apache.org/secadv.html

**Comment by RenateS** [comment]
We will be upgrading dependencies in a future version. However, these CVEs are in parts of the libraries that Holodeck B2B does not use and therefore do not pose a risk.
