### ISSUE TITLE
Getting  org.holodeckb2b.commons:generic-utils:jar:1.0.0 was not found error while building the project

### ISSUE THREAD

**Issue by sagar-lonkar** [holodeck-b2b/Holodeck-B2B#136]
Hello,

I have cloned the Git repo & tried to build project by using "mvn clean install" command from base folder , where I am getting error

[INFO] Holodeck B2B ....................................... SUCCESS [  1.087 s]
[INFO] Holodeck B2B - Interfaces .......................... SUCCESS [  5.492 s]
[INFO] Holodeck B2B - Core ................................ FAILURE [  0.195 s]
[INFO] Holodeck B2B - Default Persistency Provider ........ SKIPPED
[INFO] Holodeck B2B - Default Security .................... SKIPPED
[INFO] Holodeck B2B - Default Certificate Manager ......... SKIPPED
[INFO] Holodeck B2B - Default Security Provider ........... SKIPPED
[INFO] Holodeck B2B - ebsM3 / AS4 ......................... SKIPPED
[INFO] Holodeck B2B - User Interface ...................... SKIPPED
[INFO] Holodeck B2B - Distribution ........................ SKIPPED
[INFO] Holodeck B2B - Integration Tests ................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  7.000 s
[INFO] Finished at: 2022-10-17T18:28:55+05:30
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project holodeckb2b-core: Could not resolve dependencies for project org.holodeckb2b:holodeckb2b-core:jar:5.3.2: org.holodeckb2b.commons:generic-utils:jar:1.0.0 was not found in https://repo.maven.apache.org/maven2 during a previous attempt. This failure was cached in the local repository and resolution is not reattempted until the update interval of central has elapsed or updates are forced -> [Help 1]
[ERROR]

Please let me know if i am missing any step or configuration for building the project

**Comment by tigran-a** [comment]
Hi, 
Try first to build locally https://github.com/holodeck-b2b/generic-utils project (attention to versions)

**Comment by sagar-lonkar** [comment]
Thanks for the reply
I used 1.0.0 version & able to build project successfully.
