### ISSUE TITLE
Class SaveUserMsgAttachments: description question

### ISSUE THREAD

**Issue by tigran-a** [holodeck-b2b/Holodeck-B2B#138]
Hi, 

The class doc for SaveUserMsgAttachments says that it changes the state to READY_FOR_DELIVERY:
https://github.com/holodeck-b2b/Holodeck-B2B/blob/0af34579b1bbd7967e9493d5a3b47d7d2aedae34/modules/holodeckb2b-ebms3as4/src/main/java/org/holodeckb2b/ebms3/handlers/inflow/SaveUserMsgAttachments.java#L63

However I don't see where it happens. If I understand right, this state is assigned to User Message by the  PerformCustomValidations handler. Am I missing something? 

Thank you

**Comment by RenateS** [comment]
You are correct, the Javadoc needs to be updated here. We will fix this in the next release.
