### ISSUE TITLE
Send a Signing message with a gzip attachment

### ISSUE THREAD

**Issue by AlbertTse** [holodeck-b2b/Holodeck-B2B#143]
Hi,

I configured Pmode with "signing" property. 
![Sender_Pmode_Signing](https://user-images.githubusercontent.com/121850337/210313811-2aee5d12-4faa-442f-9e61-60e7cd0976b2.jpg)
When I send out message with "gzip" attachment, 
![Sender_mmd_gzip_attachment](https://user-images.githubusercontent.com/121850337/210313640-89072394-0543-4e20-8ec1-751b4eddc5cc.jpg)
"Authentication of message unit failed" error show.
![ErrorMsg_Authentication of message unit failed](https://user-images.githubusercontent.com/121850337/210313039-9cc01272-827e-4859-9d5c-925bec29b549.jpg)

If I send out message with a simple document attachment (e.g., xml), it works.

Any additional configuration is required for "gzip" attachment? Does it support signing with a gzip attachment?

Pmode / mmd files as follow
1. Sender Pmode setting:
[Sender_Pmode_ex-pm-push-auth-init_with_sign.txt](https://github.com/holodeck-b2b/Holodeck-B2B/files/10334734/Sender_Pmode_ex-pm-push-auth-init_with_sign.txt)
2. Receiver Pmode setting:
[Receiver_Pmode_ex-pm-push-auth-resp_with_sign.txt](https://github.com/holodeck-b2b/Holodeck-B2B/files/10334742/Receiver_Pmode_ex-pm-push-auth-resp_with_sign.txt)
3. mmd with "gzip" attachment
[Sender_msg_ex-mmd-push-auth_with_sign_gzip.mmd.txt](https://github.com/holodeck-b2b/Holodeck-B2B/files/10334770/Sender_msg_ex-mmd-push-auth_with_sign_gzip.mmd.txt)
4. mmd with simple xml attachment
[Sender_msg_ex-mmd-push-auth_with_sign_xml.mmd.txt](https://github.com/holodeck-b2b/Holodeck-B2B/files/10334773/Sender_msg_ex-mmd-push-auth_with_sign_xml.mmd.txt)

**Comment by sfieten** [comment]
Hi @AlbertTse,
please note that compression of the payloads can only be enabled in the P-Mode by adding a `//UserMessageFlow/PayloadProfile/UseAS4Compression` element with value _true_. This means that in you "gzip" scenario the compression feature is not used and the payload and its meta-data is sent as is, meaning that the MIME type of the attachment is incorrectly indicated as _application/xml_. This probably causes the signature validation to fail as XML attachment are processed differently than other file types.
