### ISSUE TITLE
Reason for fixed MSH

### ISSUE THREAD

**Issue by pkypkygit** [holodeck-b2b/Holodeck-B2B#144]
Hello.

Default receiving URL was changed to `/holodeck2b2/as4` in version 4.0 .  
The possibility to set receiving URL was removed in version 5.0.

Any reason for this? To be able to replace existing implementation with a new holodeck based one I would prefer to be able to set receiving URL. That would make the deployment much easier - as I wouldn't have to ask all the other parties to replace the sending URL on their side.

Regards, Pavel

**Comment by sfieten** [comment]
Hi Pavel,
the reason for using the fixed URLs is that the pattern is used to determine how to handle a request. If for example the [AS2 extension](https://github.com/holodeck-b2b/hb2b-as2) is added to a deployment `/holodeckb2b/as2` will ensure that the AS2 protocol implementation is used for handling the request.
If you want to use a different URL for receiving message we recommend to use a reverse proxy and redirect the request to the internal Holodeck B2B URL.
