### ISSUE TITLE
Support for BDEW AS4 profile - Electricity in Germany

### ISSUE THREAD

**Issue by ilicalex** [holodeck-b2b/Holodeck-B2B#150]
Hello,
Do you have support for BDEW AS4 profiles in existing Holodeck B2B solution?
Is there any documentation for using German BDEW BDEW AS4 profile?
BDEW - Bundesverband der Energie- und Wasserwirtschaft (German Association of Energy and Water Industries) sets the rules for German TSOs (AMPRION, 50Hz, Tennet, Transnet BW) as members of ENTSOE (The European Network of Transmission System Operators for Electricity) which includes AS4 communication in its core

Thank you in advance an best regards,
Aleksandar Ilić

**Comment by sfieten** [comment]
Hello Aleksandar,
as the BDEW profile uses cryptographic algorithms that are not part of the AS4 or WS-Security standards and not yet part of the security library, it requires additional development work. See also issue #147 that is about implementation of these new algoirthms. As these issues are so similar I will close this one.
