### ISSUE TITLE
Documentation improvement for "Getting started" and "User interfaces" pages

### ISSUE THREAD

**Issue by rkuebert** [holodeck-b2b/Holodeck-B2B#154]
Hello Holodeck-B2B team!

I just used the "Getting Started" guide (https://holodeck-b2b.org/documentation/getting-started/) to successfully deploy Holodeck-B2B as described with an "A" and a "B" instance and could successfully transfer data. Thank you for the good documentation! :)

I have the following small proposal for improvement for the documentation. In section "Configure", point 5 is "Change the port configuration". To this point, it should be added that for the "B" instance, the port for the "monitorAPI" should be set to something other than the default 1701. If not, only one instance can be accessed by the monitoring tools. Proposal for a code snippet:

```
   <worker name="monitorAPI" activate="true" delay="10"
	   workerClass="org.holodeckb2b.ui.api.RMIServer">
	   <parameter name="port">1702</parameter>
    </worker>   
```
To the same subject, it could be added on the "User interfaces" guide (https://holodeck-b2b.org/documentation/user-interfaces/) that the Graphic UI takes an optional port argument as well. For the Command Line client, this is at least clear from the "Usage" information given when invoking it without parameters. The Graphic UI has no usage message and by default connects to port 1701 (CoreInfo.DEFAULT_PORT).

Kind regards

Roland Kübert

**Comment by RenateS** [comment]
Thank you for this suggestion! We agree and will update the documentation.
