### ISSUE TITLE
Receiving a User Message with empty PayloadInfo

### ISSUE THREAD

**Issue by jaxgibbatamp** [holodeck-b2b/Holodeck-B2B#16]
If my received message has no attachments, but the SOAP envelope explicitly states
ns2:PayloadInfo/
this throws
            throw new PackagingException("PayloadInfo does not contain PartInfo elements");

thereafter, the message has a generated error for the header, & no further processing occurs - which means that any call to 
MessageContextUtils.getPrimaryMessageUnit(mc).entity
will generate a null-pointer, as there are no primary message units left.

According to the spec, PartInfo can occur 0 or more times.

**Comment by sfieten** [comment]
Closing the issue as it cannot be reproduced in version 3.1.2.
