### ISSUE TITLE
WSS4J problem - 2.0.7 available

### ISSUE THREAD

**Issue by phax** [holodeck-b2b/Holodeck-B2B#17]
Hi Sander!
Your POM uses still WSS4J 2.0.4 and the link to the issue no longer exists.
Can you please check if WSS4J 2.0.7 solves the problem (or even version 2.1.5)
Thanks

**Comment by sfieten** [comment]
Although 2.0.7 seems to be only a patch version with minor updates it includes also a new (patch) version of xmlsec which is not compatible with the current version. Integration of 2.0.7 or 2.1.x therefore requires some refactoring. 
As everything works correct now, this has low priority and  is something for a future version.
