### ISSUE TITLE
Second P-Mode is ignored according to holodeckb2b.log

### ISSUE THREAD

**Issue by ilicalex** [holodeck-b2b/Holodeck-B2B#60]
Info:
Holodeck B2B 2.1.2
Windows Server 2012R2
JRE 1.8.0.121

Is it possible to set more than one P-Mode to cover communication with several partners? If yes, why I do see in the log that PModeWatcher detects only the first p-mode in ex-pm-push-resp.xml on B side? Thank you in advance for your answer.

Best regards,
Aleksandar Ilić

**Comment by sfieten** [comment]
Hi Aleksandar,
it is possible to configure multiple P-Modes. But each P-Mode needs to be in a separate XML file. If I understand correctly you have added multiple P-Modes in on file? That would explain why only one P-Mode is picked up.

**Comment by ilicalex** [comment]
Yes, that did the trick. I just created a copy XML file, change and make sure that XML file contains only one PMode definition with uniwue P-Mode ID,
