### ISSUE TITLE
Status of sent file based on actual status

### ISSUE THREAD

**Issue by ilicalex** [holodeck-b2b/Holodeck-B2B#65]
When I change extension from e.g. accepted to .mmd I always end up with changed extension .accepted.
This behavior is OK, when the message is delivered by the holodeck b2b, but the status is the same when the message is just sent and the error on the other side prevents the payload to be delivered on the expected receiver’s folder.
Is there any way to configure this behavior?

Thank you in advance and best regards!

**Comment by sfieten** [comment]
No, this default submitter does only inform about whether it could submit the message to the Holodeck B2B core. If you want to have different processing you will need to create a custom extension.

**Comment by ilicalex** [comment]
Thaynk you for the quick answer.
