### ISSUE TITLE
Unable to construct the xenc:EncryptedKey element despite using KeyTransport and its  child elements

### ISSUE THREAD

**Issue by ilicalex** [holodeck-b2b/Holodeck-B2B#66]
Following ENTSOG AS4 profile, I must encrypt the payload (XML attachment). Based on P-Mode documentation (http://holodeck-b2b.org/documentation/p-mode-schema/):
“Element tns:EncryptionConfiguration / tns:KeyTransport
This OPTIONAL element contains the settings to add the key transport information to the WS-Security header, i.e. to construct the xenc:EncryptedKey element.
NOTE: If this element is included in the P-Mode it SHOULD contain at least one child element.”
Instead of full XML structure I end up without the second half of the XML structure (xenc:EncryptedKey and xenc:EncryptedData):
![holodeckecrypt](https://user-images.githubusercontent.com/28752131/27034479-26f1e12c-4f7e-11e7-9c3a-6245a00ecf39.png)

**Used P-Mode part:**
`<Initiator>
	<PartyId>PartnerA</PartyId>        
	<Role>ZSO</Role>				
	<SecurityConfiguration>
		 <Signing>
			<KeystoreAlias password="12345678">testCertPrivate</KeystoreAlias>
			<KeyReferenceMethod>KeyIdentifier</KeyReferenceMethod>
		</Signing>			
		<Encryption>				
			<KeystoreAlias>testCertPublic</KeystoreAlias>				
			<Algorithm>http://www.w3.org/2009/xmlenc11#aes128-gcm</Algorithm>
			<KeyTransport>                    
				<Algorithm>http://www.w3.org/2009/xmlenc11#rsa-oaep</Algorithm>
				<MGFAlgorithm>http://www.w3.org/2009/xmlenc11#mgf1sha256</MGFAlgorithm>
				<DigestAlgorithm>http://www.w3.org/2001/04/xmlenc#sha256</DigestAlgorithm>
				<KeyReferenceMethod>KeyIdentifier</KeyReferenceMethod>
			 </KeyTransport>				
		</Encryption>			
	</SecurityConfiguration>			
</Initiator>
`

**Comment by sfieten** [comment]
Dear @ilicalex, can you please be more specific of the issue you're experiencing as it is not clear to me? The included XML extract does not seem from a AS4 message generated by Holodeck B2B...

**Comment by ilicalex** [comment]
Dear Mr. Sander Fieten,

Steps to reproduce the problem:

1.    Set P-Mode on both sides to send/receive attachment, which is gzipped and encrypted.

Sender: ex-pm-push-init.xml, receiver: plinovodi.xml

2.    Digitally sign the whole message

I used the same certificate, but I used public key part to encrypt attachment and private key part to sign the message on sender side. On receiver side, I used public key to check signature and private key to decrypt the content.

3.    Renamed the file in msg_out folder (simple wrapper) for simple xml payload to .mmd.
I used WireShark to capture SOAP request on the receiver side.
The message was delivered and I was able to see the TEST XML content as payload on the receiver side. However, captured SOAP was unexpected. Check the soap part in attached wireshark text. I was hoping to get XML (SOAP request) which has xenc:EncryptedKey part in wsse:security SOAP structure as stated in the documentation.

The actual cause of the problem was my intention to set P-Mode correctly on receiver side.
I captured partner’s SOAP request with wireshark (plinovodi-SOAP.txt contains security part only) and used my infrastructure (holodeckb2b on both sides) to simulate partner’s request. However I am unable to produce partner’s xenc:EncryptedKey part in wsse:security SOAP structure.

Best regards!

**Comment by sfieten** [comment]
HI @ilicalex, 
I guess the sender's P-Mode does not specify encryption, so I advice to check the P-Mode again. As this seems more a support question then a technical problem in the software I like to point you to  http://holodeck-b2b.org/support for more information on getting support.

**Comment by ilicalex** [comment]
Hi @sfieten,
Part of sender's P-Mode is visible in original post (Used P-Mode part). I used encryption as specified in the documentation. Is there any newer version of P-Mode documentation other than one on the holodeckb2b site. If not, this is a technical problem.

**Comment by sfieten** [comment]
Hi @ilicalex,
the P-Mode documentation regarding the security configuration has not changed. I just looked at the P-Mode extract in the description and notice the encryption configuration is in the wrong place. As described in the P-Mode documentation you need to configure the encryption as a descendant of the Initiator/Responder element corresponding to the partner to which the message are sent. In your case this is the Responder.

**Comment by ilicalex** [comment]
Thank you @sfieten. Based on your hint I was able to get encrypted attachment in signed message.
Sender (initiator) and responder security part on the sender side was:
`<Initiator>
        <PartyId >OurId</PartyId>        
		<Role>ZSO</Role>						
		<SecurityConfiguration>
			 <Signing>
				<KeystoreAlias password="12345678">privateCert</KeystoreAlias>
				<KeyReferenceMethod>KeyIdentifier</KeyReferenceMethod>
            </Signing>
		</SecurityConfiguration>
    </Initiator>
<Responder>
        <PartyId>PartyId</PartyId>        
        <Role>ZSH</Role>
		<SecurityConfiguration>
			<Encryption>				
			    <KeystoreAlias>publicCert</KeystoreAlias>				
				<Algorithm>http://www.w3.org/2009/xmlenc11#aes128-gcm</Algorithm>
				<KeyTransport>                    
                    <Algorithm>http://www.w3.org/2009/xmlenc11#rsa-oaep</Algorithm>
                    <MGFAlgorithm>http://www.w3.org/2009/xmlenc11#mgf1sha256</MGFAlgorithm>
                    <DigestAlgorithm>http://www.w3.org/2001/04/xmlenc#sha256</DigestAlgorithm>
					<KeyReferenceMethod>KeyIdentifier</KeyReferenceMethod>
                 </KeyTransport>				
			</Encryption>
		</SecurityConfiguration>			
    </Responder>`

On the receiver side:
 `<Initiator>
        <PartyId>PartyId</PartyId>
        <Role>ZSO</Role>						
		<SecurityConfiguration>									
			<Signing>
				<KeystoreAlias>publicCert</KeystoreAlias>				
				<KeyReferenceMethod>KeyIdentifier</KeyReferenceMethod>
			</Signing>	
		</SecurityConfiguration>
    </Initiator>
    <Responder>
        <PartyId>OurId</PartyId>        
        <Role>ZSH</Role>
		<SecurityConfiguration>						
			<Encryption>
				<KeystoreAlias password="12345678">geniprivate</KeystoreAlias>
				<Algorithm>http://www.w3.org/2009/xmlenc11#aes128-gcm</Algorithm>				
				<KeyTransport>                    
                    <Algorithm>http://www.w3.org/2009/xmlenc11#rsa-oaep</Algorithm>
                    <MGFAlgorithm>http://www.w3.org/2009/xmlenc11#mgf1sha256</MGFAlgorithm>
                    <DigestAlgorithm>http://www.w3.org/2001/04/xmlenc#sha256</DigestAlgorithm>
					<KeyReferenceMethod>KeyIdentifier</KeyReferenceMethod>
                 </KeyTransport>				 
			</Encryption>					
		</SecurityConfiguration>
    </Responder>
`
