### ISSUE TITLE
Certificate questions

### ISSUE THREAD

**Issue by ilicalex** [holodeck-b2b/Holodeck-B2B#67]
Is there more documentation on CertificateRevocationCheck if it set to TRUE on global level?
How to force certificate hierarchy check? 
Is storing all the Certified Authorities in trustedcerts.jks the correct approach?
Should we always have chain of certificates in privatekeys.jks?

Thank you inadvance and best regards!

**Comment by RenateS** [comment]
Dear Alex, 

Certificate revocation checks are currently not supported. 

The issues you have opened are support questions, not software issues. Please see http://holodeck-b2b.org/support 

Thanks!
