### ISSUE TITLE
Encoding of SOAP attachement

### ISSUE THREAD

**Issue by jaksarx** [holodeck-b2b/Holodeck-B2B#68]
Hello,
I have the following setup. I'm on sender-initiator side using Holodeck B2B 2.1.2, Windows Server 2012R2, JRE 1.8.0.121.
When sending a message to this particular partner the message attachement content type as inspected on the wire is application/octet-stream and content transfer encoding binary. In this case our partner is expecting to receive attachements in base64 encoding (Content-Transfer-Encoding: base64).

My question is: Is it possible to specify attachement encoding being base64?

Thank you, Robert

**Comment by sfieten** [comment]
Hi Robert,
setting of the _Content-Transfer-Encoding_ MIME part header is not supported.

Please also note this issue tracker is intended for reporting bugs found in the software and not for asking questions or getting support. Please see our website for details how to [contact us](http://holodeck-b2b.org/contact/) or [get support](http://holodeck-b2b.org/support/).
