### ISSUE TITLE
Transport receiver does not open HTTPS listening port

### ISSUE THREAD

**Issue by jaksarx** [holodeck-b2b/Holodeck-B2B#73]
According to ENTSOG inbound and outbound connections must be HTTPS.
Specifying HTTPS transport receiver in axis2.xml configuration using the following does not open listening port (netstat –a does not list specified port as listening):

	<transportReceiver name="https" class="org.apache.axis2.transport.http.AxisServletListener">  
		<parameter name="port">9090</parameter>  
	</transportReceiver>  

As this is mandatory setting it would be a good idea to include HTTPS setting in your documentation.

Thank you,
	Robert

**Comment by jaksarx** [comment]
In addition to my reported issue:
I'm on receiver side using Holodeck B2B 2.1.2, Windows Server 2012R2, JRE 1.8.0.121.

**Comment by RenateS** [comment]
Hi Robert,
As we said in the previous issue you opened for a support question, this issue tracker is intended for reporting bugs found in the software and _not_ for asking questions or getting support. 
Please see our website for details how to [contact us](http://holodeck-b2b.org/contact/) or [get support](http://holodeck-b2b.org/support/).
Information on HTTPS is already included on our website, see the [Features](http://holodeck-b2b.org/features/) page.

**Comment by phax** [comment]
http://holodeck-b2b.org/features/ states "https via external proxy"
