### ISSUE TITLE
Hardcoded persistency provider using embedded Derby database

### ISSUE THREAD

**Issue by thof** [holodeck-b2b/Holodeck-B2B#74]
Hi Sander,
It seems that since version 3.0.x you've decided to drop support for persistence.xml file and hardcoded persistency provider using embedded Derby database. It's very unfortunate decision for people like me who use client-server setup of Derby (e.g. in order to have an access to DB from multiple clients).

Since I'm still on 2.1.3 and planning upgrade to 3.0.1 I performed some tests and it's enough to change two properties inside the EntityManagerUtil class:
```
props.put(org.hibernate.cfg.AvailableSettings.DRIVER, "org.apache.derby.jdbc.ClientDriver");
props.put(org.hibernate.cfg.AvailableSettings.URL, "url here");
```
It works fine but it requires from me to recompile holodeckb2b-persistency module and of course I'd like to avoid any changes inside the core of Holodeck B2B at all cost. Mostly for maintenance and upgrade reasons.

How do you think we should deal with such issue? Maybe you could parametrize these two parameters so they are provided from holodeckb2b.xml conf file?

**Comment by RenateS** [comment]
Dear Anon,

You're right; version 3.0 we’ve further modularised Holodeck B2B, as we believe that this makes the software more flexible and versatile. Based on user request we have started with the storage of message meta-data. This means that persistency functionality has now been moved into a separate module with its own API for communication with the Core module. 
I’d like to mention that Holodeck B2B is not subsidised or sponsored, but developed by a business. We believe in _libre_ open source software, but there are limits to what we can provide for free. Therefore we provide a fully functional and easy to deploy open source and free version suitable for setting up smaller gateways.  
It sounds like the company you work for is looking for an ‘enterprise strength’ gateway - we’d be happy to help you with that. Feel free to [contact us](http://chasquis-consulting.com/contact/) if you’d like to discuss this. 
Thanks!
