### ISSUE TITLE
Resource leak due to unclosed Base64 writer

### ISSUE THREAD

**Issue by radlewand** [holodeck-b2b/Holodeck-B2B#79]
There is a bug in the SingleXMLDeliverer class which may result in loss of some characters at the end of the payload messages (in my case some EDI messages were missing ending characters therefore couldn't be parsed). The problem is in the method writeEncodedPayload where you call b64os.flush() but forget about b64os.close(). 
Please note that lack of close()  generates warning "resource leak" but it was somehow ignored in the code.

**Comment by sfieten** [comment]
There indeed was an issue with the base64 encoding not being completed correctly. This is now fixed in version 3.1.0.
Calling b64os.close() doesn't work since it would also close the underlying output stream. But that needs to stay open to write further payloads and closing tags to the file.
