### ISSUE TITLE
Have Holodeck write response from remote MSH to disk

### ISSUE THREAD

**Issue by DJGummikuh** [holodeck-b2b/Holodeck-B2B#85]
Hello! 
I'm currently trying to use Holodeck on a File-System only basis. For that to work properly I require Holodeck to give me a receipt for every File I try to transmit via it to a remote partner. Currently I only get a receipt when the remote partner successfully processes my message and a "Missing Receipt" message when no receipt was received at all. However, I would also like to get the error reports from the remote partner as file (e.g. PartyId or Role wrong etc). I already tried out the SignalDelivery plugin but could not figure out how to make it work properly. Also, I actually don't really know if that plugin is what I want in the first place. At the moment there are just too many screws to make adjustments to :-(

So if anybody could help me get my bearings it would be appreciated.
- Send files encrypted and signed to a remote partner [works]
- Have Holodeck process the Response from the remote partner [works]
- Have Holodeck configured in such a way that Error Reports from the remote partner - just as successful receipts - are written to disk in a folder designated in the p-mode configuration [does NOT work]

Attached is a configuration file I currently use for testing (why tf does Github not support XML natively?)
[p-mode-config.txt](https://github.com/holodeck-b2b/Holodeck-B2B/files/2012270/p-mode-config.txt)

**Comment by sfieten** [comment]
Hi, if you see that _MissingReceipt_ are written to the specified folder the error notification is configured correctly and works since the _MissingReceipt_ is just a specific instance of an error. So I wonder if the partner does send a (valid) Error response...
If you require more assistance with this issue, we can offer consultancy services.

**Comment by DJGummikuh** [comment]
I did some debugging and have the feeling that there is a bug in your Error Signal handling. DeliverErrors.doProcessing checks if it can change the State for the Signal from READY_FOR_DELIVERY to OUT_FOR_DELIVERY - however since we're handling a REPLY to an already failed transmission the State is FAILED. I'm trying to figure out what actually needs to happen here, still lacking too much of understanding for your code but apparently you should not only check for original state READY_FOR_DELIVERY but also FAILURE to accomodate handling of error signals from the receiving as4 implementation.

**Comment by DJGummikuh** [comment]
Short update: 
I replaced
`if(updateManager.setProcessingState(errorSignal, ProcessingState.READY_FOR_DELIVERY, ProcessingState.OUT_FOR_DELIVERY)) {`

with 
`if(updateManager.setProcessingState(errorSignal, ProcessingState.READY_FOR_DELIVERY, ProcessingState.OUT_FOR_DELIVERY) || updateManager.setProcessingState(errorSignal, ProcessingState.FAILURE, ProcessingState.OUT_FOR_DELIVERY)) {`

And it satisfies both all your tests and is now allowing holodeck to handle error responses much the same way like MissingReceipt Errors.

**Comment by sfieten** [comment]
Yes, that might work. But it certainly isn't the correct way of doing it since you're now delivering all Errors, also the ones that are found to be invalid and should have failed. 
Please provide the information logged on the errors from the _ebms__errors.log_ and _soap__in.log_ so I can check what may the issue here.

**Comment by DJGummikuh** [comment]
[ebms_errors.log](https://github.com/holodeck-b2b/Holodeck-B2B/files/2013288/ebms_errors.log)
[soap_in.log](https://github.com/holodeck-b2b/Holodeck-B2B/files/2013289/soap_in.log)

Though what I don't get is, what is an "invalid" error in this constellation? False Positive? Because basically I want every error that occurs to be presented
