### ISSUE TITLE
Web Service WDSL interface

### ISSUE THREAD

**Issue by lupindeterd** [holodeck-b2b/Holodeck-B2B#88]
Is there a Web Service interface that exposes WDSL  that I use with non Java language? e.g., Python

**Comment by RenateS** [comment]
No. Assuming you want to exchange AS4 messages with Holodeck B2B the message structure and processing is specified in the [AS4 standard](http://docs.oasis-open.org/ebxml-msg/ebms/v3.0/profiles/AS4-profile/v1.0/os/AS4-profile-v1.0-os.html). There is no WSDL available for this. If you want to _use_ Holodeck B2B for exchanging AS4 messages (ie communicating with your partners) you'll find an introduction in the [Getting Started](http://holodeck-b2b.org/documentation/getting-started/) guide. 
Connecting with Holodeck B2B can be done using the API in the Interfaces module.
