### ISSUE TITLE
Severity attributes should be "warning" or "failure" not "WARNING" or "FAILURE".

### ISSUE THREAD

**Issue by fhouweling** [holodeck-b2b/Holodeck-B2B#89]
Axway B2Bi does not recognize error messages with the severity in capitals.
We issued a support case for B2Bi but according to Axway the severity should be lowercase:

AS4 is based on XML and XML is case sensitive. Therefore, anything in the spec must be regarded as case sensitive and the spec is clear that the REQUIRED attribute value is either "warning" or "failure". Not WARNING nor FAILURE. If we were to change this, we would be violating the spec.

See http://docs.oasis-open.org/ebxml-msg/ebms/v3.0/core/ebms_core-3.0-spec.pdf
Chapter: "6 Error Handling"
Section: "6.2.5. eb:Error/@severity"

2196 6.2.5. eb:Error/@severity
2197 This REQUIRED attribute indicates the severity of the error. Valid values are: warning, failure.
2198 The warning value indicates that a potentially disabling condition has been detected, but no m essage
2199 processing and/or exchange has failed so far. In particular, if the message was supposed to be delivered
2200 to a consumer, it would be delivered even though a warning was issued. Other related messages in the
2201 conversation or MEP can be generated and exchanged in spite of this problem.
2202 The failure value indicates that the processing of a message did not proceed as expected, and cannot
2203 be considered successful. If, in spite of this, the message payload is in a state of being delivered, the
2204 default behavior is not to deliver it, unless an agreement states otherwise (see OpCtx-ErrorHandling).
2205 This error does not presume the ability of the MSH to process other messages, although the
2206 conversation or the MEP instance this message was involved in is at risk of being invalid.

**Comment by sfieten** [comment]
This issue will be resolved in next release of version 3.1 and 4.0. The code is already available in branches [R-3.x](https://github.com/holodeck-b2b/Holodeck-B2B/tree/R-3.x) and [next (version 4.0)](https://github.com/holodeck-b2b/Holodeck-B2B/tree/next)

**Comment by fhouweling** [comment]
Thanks for the quick response!
