### ISSUE TITLE
Chasquis-Consulting email not working?

### ISSUE THREAD

**Issue by zunzster** [holodeck-b2b/Holodeck-B2B#93]
Hi

Sorry to be posting this here but I was running out of ideas.

Back in November last year, I can into a problem where email to info@chasquis-consulting.com was bouncing. So I posted here and Renate sent an email to me.

I've tried replying to her email from renate@chasquis-consulting.com about purchasing consulting twice: once on the 3rd of December and again last week on the 8th of March. 

I've heard nothing back on either email (not even a bounce), so now I'm wondering if maybe some other email issue (spam filter?) is swallowing my replies to Renate so she isn't seeing them. 

Is there some other convenient method of making contact I should use instead?
I can be reached at paul@accredo.co.nz

Cheers,
  Paul.

**Comment by RenateS** [comment]
Hi Paul,
an email is on its way to you!
